name: build

on:
  push:
    paths:
      - '_react/*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - name: Deploy Info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Install
      run: yarn --cwd _react install
    - name: Build
      run: yarn --cwd _react build
    - name: Test
      run: yarn --cwd _react test
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: yarn publish _react --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
