name: build

on:
  push:
    paths:
      - 'packages/react/*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.9'
        registry-url: 'https://registry.npmjs.org'
    - name: Deploy Info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Install
      run: yarn --cwd react install
    - name: Build
      run: yarn --cwd react build
    - name: Test
      run: yarn --cwd react test
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: yarn publish packages/react --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
